name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
#    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: >
         cd hex; make;
         cd ../maximum_path_sum; make;
# needs libtbb and stdc++17         cd ../parallel_algorithms; make;
         
